<a href="https://colab.research.google.com/github/subh007/ml-ground/blob/main/Day_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install tensorflow

In [3]:
import tensorflow as tf

In [4]:
tf.config.list_physical_devices('GPU')

[]

In [5]:
b = tf.ones(shape=(3,5))

In [6]:
b

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [7]:
b + 10

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.]], dtype=float32)>

In [8]:
b.numpy()

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)

In [9]:
(train_x, train_y), (test_X, test_Y) = tf.keras.datasets.boston_housing.load_data(test_split=0)

57026/57026 ━━━━━━━━━━━━━━━━━━━━ 0s 1us/step


In [10]:
tf.__version__

'2.17.1'

In [11]:
type(train_x)

numpy.ndarray

In [12]:
train_x.shape

(506, 13)

In [13]:
train_x

array([[1.23247e+00, 0.00000e+00, 8.14000e+00, ..., 2.10000e+01,
        3.96900e+02, 1.87200e+01],
       [2.17700e-02, 8.25000e+01, 2.03000e+00, ..., 1.47000e+01,
        3.95380e+02, 3.11000e+00],
       [4.89822e+00, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        3.75520e+02, 3.26000e+00],
       ...,
       [1.83377e+00, 0.00000e+00, 1.95800e+01, ..., 1.47000e+01,
        3.89610e+02, 1.92000e+00],
       [3.58090e-01, 0.00000e+00, 6.20000e+00, ..., 1.74000e+01,
        3.91700e+02, 9.71000e+00],
       [2.92400e+00, 0.00000e+00, 1.95800e+01, ..., 1.47000e+01,
        2.40160e+02, 9.81000e+00]])

In [25]:
train_x.dtype

dtype('float64')

In [26]:
train_x = train_x.astype('float32')
train_y = train_y.astype('float32')

In [15]:
w = tf.zeros(shape=(13,1))

In [24]:
w

<tf.Tensor: shape=(13, 1), dtype=float32, numpy=
array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]], dtype=float32)>

In [17]:
b = tf.zeros(shape=(1))

In [23]:
b

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.], dtype=float32)>

In [19]:
def predict(X, w, b):
  return tf.matmul(X, w) + b


In [27]:
predictions = predict(train_x, w, b)

In [28]:
predictions

<tf.Tensor: shape=(506, 1), dtype=float32, numpy=
array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
 

In [ ]:
def x_gradient(X, Y, Y_hat):
  return tf.transpose(X) @ (Y_hat - Y)

In [43]:
train_y.shape

(506,)

In [35]:
def loss(Y, Y_hat):
  return tf.reduce_mean(tf.square(Y_hat - Y))

In [36]:
cost = loss(train_y, predictions)

In [37]:
cost

<tf.Tensor: shape=(), dtype=float32, numpy=592.14685>

In [39]:
def train(X, Y, w, b, learning_rate=0.01):
  with tf.GradientTape() as tape:
    tape.watch([w, b])
    predictions = predict(X, w, b)
    cost = loss(Y, predictions)
  dw, db = tape.gradient(cost, [w, b])
  w = w - learning_rate * dw
  b = b - learning_rate * db
  return w, b

In [40]:
new_w, new_b = train(train_x, train_y, w, b)

In [44]:
new_w.shape

TensorShape([13, 1])