<a href="https://colab.research.google.com/github/subh007/ml-ground/blob/main/time_series.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
! pip install tensorflow

In [2]:
import tensorflow as tf
import tensorflow_datasets as tfds

In [3]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("robervalt/sunspots")

print("Path to dataset files:", path)

100%|██████████| 22.4k/22.4k [00:00<00:00, 23.5MB/s]

Extracting files...
Path to dataset files: /root/.cache/kagglehub/datasets/robervalt/sunspots/versions/3


In [4]:
import pandas as pd

In [5]:
df = pd.read_csv(path + "/Sunspots.csv")

In [6]:
df.head()

Unnamed: 0        Date  Monthly Mean Total Sunspot Number
0           0  1749-01-31                               96.7
1           1  1749-02-28                              104.3
2           2  1749-03-31                              116.7
3           3  1749-04-30                               92.8
4           4  1749-05-31                              141.7

In [7]:
df.shape

(3265, 3)

In [8]:
df.size

9795

In [9]:
dataset = tf.keras.utils.timeseries_dataset_from_array(df['Monthly Mean Total Sunspot Number'][:-3], df['Monthly Mean Total Sunspot Number'][3:],sequence_length=3, batch_size=2)

In [10]:
dataset

<_BatchDataset element_spec=(TensorSpec(shape=(None, None), dtype=tf.float64, name=None), TensorSpec(shape=(None,), dtype=tf.float64, name=None))>

In [11]:
for X, y in dataset:
    print("X (Input):", X.numpy(), "→ y (Future Target):", y.numpy())

X (Input): [[ 96.7 104.3 116.7]
 [104.3 116.7  92.8]] → y (Future Target): [ 92.8 141.7]
X (Input): [[116.7  92.8 141.7]
 [ 92.8 141.7 139.2]] → y (Future Target): [139.2 158. ]
X (Input): [[141.7 139.2 158. ]
 [139.2 158.  110.5]] → y (Future Target): [110.5 126.5]
X (Input): [[158.  110.5 126.5]
 [110.5 126.5 125.8]] → y (Future Target): [125.8 264.3]
X (Input): [[126.5 125.8 264.3]
 [125.8 264.3 142. ]] → y (Future Target): [142.  122.2]
X (Input): [[264.3 142.  122.2]
 [142.  122.2 126.5]] → y (Future Target): [126.5 148.7]
X (Input): [[122.2 126.5 148.7]
 [126.5 148.7 147.2]] → y (Future Target): [147.2 150. ]
X (Input): [[148.7 147.2 150. ]
 [147.2 150.  166.7]] → y (Future Target): [166.7 142.3]
X (Input): [[150.  166.7 142.3]
 [166.7 142.3 171.7]] → y (Future Target): [171.7 152. ]
X (Input): [[142.3 171.7 152. ]
 [171.7 152.  109.5]] → y (Future Target): [109.5 105.5]
X (Input): [[152.  109.5 105.5]
 [109.5 105.5 125.7]] → y (Future Target): [125.7 116.7]
X (Input): [[105.5 12